server:
  port: 9002
  allowed_origins: http://localhost:4200

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      name: teste
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3309/rideshare
    username: root
    password: t00R
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  service-charge: 200
  charge-per-km: 20

location:
  url: http://localhost:9000/api/v1
  timeout: 2000